### ISSUE TITLE
failed on OSX

### ISSUE THREAD

**Issue by zh99998** [tobyxdd/OpenWokuan#1]
```bash
localhost:bin zh99998$ ./OpenWokuan
[22:32:34] OpenWokuan by Toby Huang
[22:32:34] An open-source Beijing Unicom Speedbooster.
[22:32:34] No account is specified in the parameters!
[22:32:34] Retrieving account information...
Exception in thread "main" java.lang.NullPointerException
	at com.tobyxdd.openWokuan.SpeedInfo.refreshInfo(SpeedInfo.java:135)
	at com.tobyxdd.openWokuan.SpeedInfo.<init>(SpeedInfo.java:118)
	at com.tobyxdd.openWokuan.AppMain.main(AppMain.java:44)
localhost:bin zh99998$
```

**Comment by tobyxdd** [comment]
应该不是和系统有关的问题 确认你在北京联通么 帐号开头几位是否是100？

**Comment by zh99998** [comment]
确认了是网络问题，是北京联通但是可能没有参与这个活动的资格。换了另一个北京联通网络后成功了。
不过最好能给个提示，而不是直接crash掉。

**Comment by kongnanlive** [comment]
怎么个提速发？10M宽带提成百兆宽带吗？
